# Generated by Django 4.2 on 2024-10-24 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goldprice', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoinPrice',
        ),
    ]
